spring.application.name=api-gateway
server.port=8765

# Eureka client config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable service discovery for gateway routes
#spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
#spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Optional: debug logging
logging.level.org.springframework.cloud.gateway=DEBUG

# Disable Spring Cloud Config check if you are not using it
spring.cloud.config.import-check-enabled=false
