spring.application.name=limits-service
spring.profiles.active=dev
spring.cloud.config.profile=dev
server.port=8080
spring.cloud.config.enable=true
spring.config.import=configserver:http://localhost:8888
limits-service.minimum=2
limits-service.maximum=998
