spring.application.name=currency-conversion-service
server.port=8100
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=false
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8761/eureka

#spring.cloud.config.enabled=false
spring.config.import-check.enabled=false

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.initial-instance-info-replication-interval-seconds=10

