spring.application.name=currency-exchange-service
server.port=8001
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=false
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

resilience4j.retry.instances.sample-api.maxAttempts=5 
#resilience4j.retry.instances.sample-api.maxRetryAttempts=5 #OLD

resilience4j.retry.instances.sample-api.waitDuration=1s
resilience4j.retry.instances.sample-api.enableExponentialBackoff=true
#resilience4j.circuitbreaker.instances.default.failureRateThreshold=90
resilience4j.ratelimiter.instances.default.limitForPeriod=2
resilience4j.ratelimiter.instances.default.limitRefreshPeriod=10s
resilience4j.bulkhead.instances.default.maxConcurrentCalls=10
resilience4j.bulkhead.instances.sample-api.maxConcurrentCalls=10
#spring.main.web-application-type=reactive